@HOST=localhost:5050
@COOKIE=sid=MTc4MjQ1NjU2N3xEWDhFQVFMX2dBQUJFQUVRQUFELUFRZl9nQUFFQm5OMGNtbHVad3dFQUFKSlJBVnBiblEyTkFRQ0FBWUdjM1J5YVc1bkRCQUFEa2xrWlc1MGFXWnBZMkYwYVc5dUJuTjBjbWx1Wnd4Q0FFQmxNVEJpWWpWa00ySXdPVEZrTXpKaVlqa3hZVEprWVdZM1kySTFOV1F5T0RZME1HWTBNall5T0RneE5HSTRZbU5oTUdSbE9ESmtOV0ZpT1RsbE1EYzJCbk4wY21sdVp3d0tBQWhRWVhOemQyOXlaQVp6ZEhKcGJtY01RZ0JBTnpWbU5HUXlaV1k0T1dGbU0yVmhOREZrTldRMk5UQmlOVFl6TURCaU5ETm1ZMlJtTXpnMFpHTmlaREJpTWpjeE4yWXhZMlJqTUdFMllqWTFaakpsWkFaemRISnBibWNNQ2dBSVRtbGphMjVoYldVR2MzUnlhVzVuREE0QURPeVZoT3lkdE91aG5PdUxpQT09fFwGrrbZDtIwtqoK39IQMSJWtnoq6XaDiqPB6NwZbRKf;

###
POST http://{{HOST}}/users
Content-Type: application/json

{
    "identification": "irony",
    "nickname": "아이로니",
    "password": "!Fa1289"
}

###

POST http://{{HOST}}/users/session
Content-Type: application/json

{
    "identification": "irony",
    "password": "!Fa1289"
}
###

GET http://{{HOST}}/users/session
#Cookie: @{{COOKIE}}

###

DELETE http://{{HOST}}/users/session
